### ISSUE TITLE
Backport switching graphics without reboot to bionic

### ISSUE THREAD

**Issue by brs17** [pop-os/system76-power#135]
Backport https://github.com/pop-os/system76-power/pull/119/ to master_bionic if possible.

**Comment by lzyang2000** [comment]
If I want to test it in 1804 - how do I build the package?
Thanks!

**Comment by mmstick** [comment]
Within the pop-os/pop repository, use the scripts/apt script to add the staging branch to your system.

**Comment by crawfxrd** [comment]
The behavior of GDM/gnome-shell after restarting `display-manager` is too unreliable to introduce this workaround in 18.04.
