### ISSUE TITLE
Dbus 0.7.1 upgrade did not go into 18.04

### ISSUE THREAD

**Issue by leviport** [pop-os/system76-power#136]
When reviewing https://github.com/pop-os/system76-power/pull/134 I noticed that it built for Bionic, but was PR'd into `master` which only merges into Eoan. Should the same Dbus update go into the `master_bionic` branch as well?

**Comment by mmstick** [comment]
Yes, we can cherry-pick the commits

**Comment by brs17** [comment]
> Yes, we can cherry-pick the commits

I would say we should cherry pick the specific commits so there can be a pr just for the Dbus update and similarly for https://github.com/pop-os/system76-power/issues/135

**Comment by crawfxrd** [comment]
#137
