### ISSUE TITLE
top bar power controls GUI changed - no option to change graphics - nvidia/intel/hybrid

### ISSUE THREAD

**Issue by joewav** [pop-os/system76-power#146]
![power settings](https://user-images.githubusercontent.com/59369646/73061225-3dd76c00-3ecc-11ea-9c16-35fcde679164.png)

pop-os 19.10 
 
 
I only get "power setting" where before I had the option of switching between nvidia and intel (or hybrid).

I've seen a similar issue reported as a bug before, but issue closed last year around April: https://github.com/pop-os/gnome-shell-extension-system76-power/issues/20

as a related side note, all the GUI for the top right menu changed: including the icon for the power charge, and also now to switch between shutdown and sleep, I need to hold down the shutdown icon until it changes to pause icon. 

Doesn't seem to be a problem to switch through terminal

**Comment by crawfxrd** [comment]
Is the extension enabled?

**Comment by joewav** [comment]
@crawfxrd all extensions were disabled 0_o 
thx
