### ISSUE TITLE
lemp9: improved high performance mode

### ISSUE THREAD

**Issue by jackpot51** [pop-os/system76-power#166]
phoronix-test-suite benchmark build-linux-kernel results:

before: 285.53
after: 241.12

Changes:
PL1: 20 -> 25
PL2: 30 -> 51
TCC: 88 -> 98
HEATUP: 10 -> 1
disable thermald through dbus

**Comment by curiousercreative** [comment]
@jackpot51 this looks resolved?

**Comment by jackpot51** [comment]
Indeed, it is
