### ISSUE TITLE
System suddenly get strct/hanged for 3-5 minutes 

### ISSUE THREAD

**Issue by ganesh1901** [pop-os/system76-power#179]
my hardware specification:
Apple All in one 
4 Gb RAM dedicated
intel Core 2 duo processer with 2.4 Ghz
2 Gb Graphics dedicated

**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

after the system get released or working fine i have collected the dmesg log 

[ 9426.062972] INFO: task GpuWatchdog:2837 blocked for more than 120 seconds.
[ 9426.062978]       Tainted: G           OE     5.4.0-7634-generic #38~1595345317~20.04~a8480ad-Ubuntu
[ 9426.062979] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 9426.062981] GpuWatchdog     D    0  2837   2788 0x00000000
[ 9426.062984] Call Trace:
[ 9426.062994]  __schedule+0x2e3/0x740
[ 9426.062997]  ? __switch_to_asm+0x40/0x70
[ 9426.062999]  ? __switch_to_asm+0x34/0x70
[ 9426.063001]  schedule+0x42/0xb0
[ 9426.063002]  io_schedule+0x16/0x40
[ 9426.063005]  wait_on_page_bit+0x11c/0x200
[ 9426.063007]  ? file_fdatawait_range+0x30/0x30
[ 9426.063009]  wait_on_page_writeback+0x43/0x90
[ 9426.063012]  shmem_swapin_page+0x23b/0x660
[ 9426.063015]  ? xas_load+0xd/0x80
[ 9426.063016]  ? find_get_entry+0x5e/0x170
[ 9426.063018]  shmem_getpage_gfp+0x3c8/0x940
[ 9426.063021]  ? page_add_file_rmap+0xff/0x1a0
[ 9426.063023]  shmem_fault+0x79/0x210
[ 9426.063025]  __do_fault+0x3c/0x130
[ 9426.063027]  do_fault+0x24b/0x640
[ 9426.063029]  __handle_mm_fault+0x4c5/0x7a0
[ 9426.063031]  handle_mm_fault+0xca/0x200
[ 9426.063034]  do_user_addr_fault+0x1f9/0x450
[ 9426.063037]  ? do_futex+0x160/0x1e0
[ 9426.063039]  __do_page_fault+0x58/0x90
[ 9426.063041]  do_page_fault+0x2c/0xe0
[ 9426.063043]  page_fault+0x34/0x40
[ 9426.063046] RIP: 0033:0x55f3e5318fbd
[ 9426.063054] Code: Bad RIP value.
[ 9426.063055] RSP: 002b:00007f288db93ea0 EFLAGS: 00010283
[ 9426.063057] RAX: 0000000000009160 RBX: 0000000000009160 RCX: 00007f288c3c5000
[ 9426.063058] RDX: 0000000000000000 RSI: 00007f288db93ecc RDI: 000055f3ea7d8670
[ 9426.063059] RBP: 00007f288db93eb0 R08: 000000000000004e R09: 0000000000040000
[ 9426.063060] R10: 637461572e555047 R11: 65726854676f6468 R12: 0000000000009160
[ 9426.063061] R13: 0000000000000009 R14: 0000000000000000 R15: 00007f288db93ecc

**Steps to reproduce (if you know):*
arbitrary happening and not able predict the time 

**Expected behavior:**

**Other Notes:**

**Comment by mmstick** [comment]
This looks to be hardware specific, and unrelated to system76-power (generic power management service)
