### ISSUE TITLE
[Request] Disable Gnome animations on "Battery Life" mode

### ISSUE THREAD

**Issue by juxuanu** [pop-os/system76-power#192]
On my laptop I have better battery life when the Gnome animations are disabled. I think it'd be nice if the animations were disabled on "Battery Life" mode and then enabled again on any of the other modes. 
Basically, `gsettings set org.gnome.desktop.interface enable-animations false` or `true` accordingly.

**Comment by kylebakerio** [comment]
Do you have data on how significant the effect is?

**Comment by crawfxrd** [comment]
Duplicate of #108.
