### ISSUE TITLE
Fans start spinning for 2 seconds when idle

### ISSUE THREAD

**Issue by pflanzenandi** [pop-os/system76-power#216]
**Normal behaviour:** The fans (CPU & GPU) only start when the threshold of > 60 °C is reached. They then run until a CPU temperature of approx. 35 °C is reached. After that, they switch off completely.

**Behaviour since today:** Even at an idle temperature of 30 °C, the fans start briefly for 2 seconds. They are then immediately stopped by the fan management. After 10 seconds the fans start again and so on.

The fan behaviour only exists when the notebook is charging. In battery mode, the fan management takes full control again. 

Pop_Os 20.10 (NVidia)
Power Settings: Integrated Graphics & Balanced
TLP 1.3.1

Dell XPS 9570:
Intel Core™ i7-8750H CPU @ 2.20GHz × 12 
Mesa Intel® UHD Graphics 630 (CFL GT2)
Nvidia Driver: 460.32.03-1pop0~1611601564.20.10.11a4029

**Comment by pflanzenandi** [comment]
When I use the following script to disable SMBIOS control, the fans run continuously. 

dell-bios-fan-control 0

https://github.com/TomFreudenberg/dell-bios-fan-control

**Comment by pflanzenandi** [comment]
A gnome extension triggered this behaviour. Can be closed.

https://extensions.gnome.org/extension/1180/freon/

**Comment by bflanagin** [comment]
Thanks for the report and self diagnosing the issue @pflanzenandi. We'll make a note of it for the next time someone has the issue!
