### ISSUE TITLE
error processing package system76-driver-nvidia (can't use hybrid/nvidia modes anymore)

### ISSUE THREAD

**Issue by HansN87** [pop-os/system76-power#350]
**Distribution (run `cat /etc/os-release`):**

 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

system76-driver-nvidia:
  Installed: 20.04.59~1657202656~22.04~7b26eb3
  Candidate: 20.04.59~1657202656~22.04~7b26eb3
  Version table:
 *** 20.04.59~1657202656~22.04~7b26eb3 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

since this morning I can't switch to nvidia or hybrid modes anymore.

**Steps to reproduce (if you know):**

not sure. I simply did the sporadic update of all available package updates through pop-shop.

**Expected behavior:**

being able to use nvidia drivers

**Other Notes:**

I found this issue (https://github.com/pop-os/system76-power/issues/296) but the accepted solution https://github.com/pop-os/system76-power/issues/296#issuecomment-1047208380 did not work for me.

See output of sudo dpkg --configure -a and notice the errors with nvidia-driver-515

```
Setting up nvidia-dkms-515 (515.48.07-1pop0~1657640780~22.04~e863eed) ...
update-initramfs: deferring update (trigger activated)
INFO:Enable nvidia
Loading new nvidia-515.48.07 DKMS files...
Consult /var/lib/dkms/nvidia/515.48.07/build/make.log for more information.
dpkg: error processing package nvidia-dkms-515 (--configure):
 installed nvidia-dkms-515 package post-installation script subprocess returned error exit status 10
dpkg: dependency problems prevent configuration of nvidia-driver-515:
 nvidia-driver-515 depends on nvidia-dkms-515 (>= 515.48.07); however:
  Package nvidia-dkms-515 is not configured yet.

dpkg: error processing package nvidia-driver-515 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of system76-driver-nvidia:
 system76-driver-nvidia depends on nvidia-driver-515 | nvidia-driver-510 | nvidia-driver-470; however:
  Package nvidia-driver-515 is not configured yet.
  Package nvidia-driver-510 is not installed.
  Package nvidia-driver-470 is not installed.

dpkg: error processing package system76-driver-nvidia (--configure):
 dependency problems - leaving unconfigured
Processing triggers for initramfs-tools (0.140ubuntu13) ...
update-initramfs: Generating /boot/initrd.img-5.17.15-76051715-generic
cryptsetup: WARNING: Resume target cryptswap uses a key file
kernelstub.Config    : INFO     Looking for configuration...
kernelstub           : INFO     System information: 

    OS:..................Pop!_OS 22.04
    Root partition:....../dev/nvme1n1p3
    Root FS UUID:........aca4352f-8d3c-4698-a63a-e041f2d741c2
    ESP Path:............/boot/efi
    ESP Partition:......./dev/nvme1n1p1
    ESP Partition #:.....1
    NVRAM entry #:.......-1
    Boot Variable #:.....0000
    Kernel Boot Options:.quiet loglevel=0 systemd.show_status=false splash
    Kernel Image Path:.../boot/vmlinuz-5.17.15-76051715-generic
    Initrd Image Path:.../boot/initrd.img-5.17.15-76051715-generic
    Force-overwrite:.....False

kernelstub.Installer : INFO     Copying Kernel into ESP
kernelstub.Installer : INFO     Copying initrd.img into ESP
kernelstub.Installer : INFO     Setting up loader.conf configuration
kernelstub.Installer : INFO     Making entry file for Pop!_OS
kernelstub.Installer : INFO     Backing up old kernel
kernelstub.Installer : INFO     Making entry file for Pop!_OS
Errors were encountered while processing:
 nvidia-dkms-515
 nvidia-driver-515
 system76-driver-nvidia
```

Any suggestions appreciated.

**Comment by leviport** [comment]
Please post output from these commands:

```
sudo apt purge ~nnvidia
sudo apt autoremove
sudo apt clean
sudo apt install nvidia-driver-515
```

Please not that the first one is not a typo. `~nnvidia` is a wildcard that matches any nvidia packages installed, and it must be typed exactly as shown.

**Comment by HansN87** [comment]
I attached the outputs as txt files @leviport 

```sudo apt purge ~nnvidia```
[purge.txt](https://github.com/pop-os/system76-power/files/9133874/purge.txt)

```sudo apt autoremove```
[autoremove.txt](https://github.com/pop-os/system76-power/files/9133881/autoremove.txt)

```sudo apt clean```
no output.

```sudo apt install nvidia-driver-515```
[install_nvidia_driver_515.txt](https://github.com/pop-os/system76-power/files/9133883/install_nvidia_driver_515.txt)

Thank you.

**Comment by HansN87** [comment]
update: manage to get it working again on my system.

looking through the logs of the failed build
```Consult /var/lib/dkms/nvidia/515.48.07/build/make.log for more information.```
I noticed errors indicating gcc version mismatch. (Now using gcc < 11 while I had been using  gcc-11 for a while).

checking my available gcc versions:
```sudo update-alternatives --config gcc```
didn't list gcc-11. 

adding it back in:
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 11

and then working from there
```
sudo dpkg --configure -a # Configure any packages not yet configured
sudo apt install -f # Fix any broken packages
sudo apt full-upgrade # Upgrade any packages that need it
sudo apt autoremove # Remove any unneeded packages still installed
sudo apt install system76-driver-nvidia # Install the nvidia driver via system76 package
sudo shutdown -r now # Reboot
```

solved it. 

Not sure what borked my gcc config leading to this issue. I haven't touched anything related in a few weeks.
Since it might have been caused by updates through pop-shop, I am leaving this open. (Feel free to close.)

**Comment by leviport** [comment]
Thanks for the report, and glad to hear it's working now. I haven't heard any other reports of this, so I'm going to close the issue for now. If additional reports crop up, we will reopen.
