### ISSUE TITLE
AMD P-State EPP doesn't change based on the selected power profile

### ISSUE THREAD

**Issue by knamroud** [pop-os/system76-power#415]
**Distribution (run `cat /etc/os-release`):**
"Pop!_OS 22.04 LTS"
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
system76-power 1.1.25\~1690395185\~22.04\~fc8eb49
kernel 6.5.4-76060504.202309191142\~1695998943\~22.04\~070916d

**Issue/Bug Description:**
AMD P-State Active isn't working properly with system76-power.
Switching power profile won't reflect the change in the epp files, leading to a not so optimized experience.
I found this bug on a Ryzen 7 5700U and a 7 5825U.

**Steps to reproduce (if you know):**
Switch to amd_pstate active (epp).
Switch power profile.
![image](https://github.com/pop-os/system76-power/assets/87078943/a000840d-7e4a-4c51-ac3f-98ca7a01ca96)
Cat the various epp files and note how it is incoherent with the selected power profile:
![image](https://github.com/pop-os/system76-power/assets/87078943/253df2e1-307c-4f73-90ff-c6f432ffc3e7)

**Expected behavior:**
Shouldn't the epp, as it is the main way in which we can control the performance of the CPU when using AMD P-State Active, change based on the power profile selected in system76-power? 
I also came across a merged pr that supposedly fixed this issue, but I'm still facing this issue on two different machines.

**Comment by mmstick** [comment]
https://github.com/pop-os/system76-power/blob/master/src/cpufreq.rs#L22-L38

Check the value of `/sys/devices/system/cpu/cpu0/cpufreq/scaling_government` and `/sys/devices/system/cpu/cpu0/cpufreq/scaling_driver`.

**Comment by mmstick** [comment]
Try branch `epp` and see if that behaves how you expect.
