### ISSUE TITLE
Will there be support for Ubuntu LTS 24.04? Could not locate package system76-driver

### ISSUE THREAD

**Issue by RuizSenior** [pop-os/system76-power#429]
**Distribution (run `cat /etc/os-release`):**
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
 
 

**Issue/Bug Description:**
Based on this page, I couldn't do the installation or I don't know how to do it
https://support.system76.com/articles/graphics-switch-ubuntu/

**Steps to reproduce (if you know):**
sudo apt-add-repository -ys ppa:system76-dev/stable
sudo apt update
sudo apt-get install -y system76-driver

**Comment by jacobgkau** [comment]
Everything's in the repo and released by now.
