### ISSUE TITLE
Daemon does not set fan to auto after termination.

### ISSUE THREAD

**Issue by cowai** [pop-os/system76-power#70]
There should be a catch of SIGTERM and other signals when the daemon is stopped for any reason, and make sure that the fan is set back to auto.

If the user runs "sudo systemctl stop system76-power" and  then starts a game or whatever, it will fry the machine :)

**Comment by jackpot51** [comment]
Good catch!

**Comment by cowai** [comment]
@jackpot51
https://github.com/cowai/pwm-better-fan-control
I put this together for my own use. This catches exit codes, and have a more comfortable fan curve and spin down process.
