### ISSUE TITLE
Set APM for HDDs

### ISSUE THREAD

**Issue by thorhop** [pop-os/system76-power#75]
```
NAME="Pop!_OS"
VERSION="19.04"
**Distribution:**
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco 
```
 
**Related Application and/or Package Version:**

hdparm:
```
  Installed: 9.58+ds-1
  Candidate:   9.58+ds-1
  Version table:
 *** 9.58+ds-1 500
        500 http://us.archive.ubuntu.com/ubuntu disco/main amd64 Packages
        100 /var/lib/dpkg/status
```

system76-power:
```
  Installed: 1.0.0~1555432002~19.04~1c347b8
  Candidate:   1.0.0~1555432002~19.04~1c347b8
  Version table:
 *** 1.0.0~1555432002~19.04~1c347b8 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu disco/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

System76-power does not set a sane APM for HDDs. The usual APM level is `254`, which resets after reboot. On an unrelated note: for some reason setting the `apm` value in `/etc/hdparm.conf` does nothing. Upon reboot it resets the value to `254`. The problem with using any value above 127 is that the disk will not spin down and be idle. My HDD has been active all the time and generates a heckin amount of heat (I've seen something close to 50 degrees celsius, even when it's not in use... which is insane). Setting it on boot is ideal and I've made a udev rule to that effect (see screenshot). But this might also be a feature that the **System76-power** daemon might want to deal with. I'm not sure...

**Steps to reproduce (if you know):**

1. Boot the system
2. Run `sudo hddparm -B /dev/sdX`
3. Be sad that you're abusing your HDD

**Expected behavior:**

That the HDD(s) have an APM level of 127 or less, so that the disk can spin down and be idle.

**Other Notes:**
If you're running a workstation and it needs to read from HDD all the time a level above `127` might be preferable. Having the full `254` levels of APM might be suitable for a server, but not a desktop. Power needs to be conserved and the lifespan of an HDD should be as long as possible.

**Files:**
![popos_system76-power_hdparm](https://user-images.githubusercontent.com/1967775/56651304-0d3a7b80-6689-11e9-9fbe-5d89ab1db886.png)

**Comment by mmstick** [comment]
Closing because we already support for this.
