### ISSUE TITLE
[fan] account for GPU temperatures

### ISSUE THREAD

**Issue by jackpot51** [pop-os/system76-power#81]
In a test case on a 4 GPU Thelio Massive, GPU temps approached 90 C while the CPU temps stayed around 40 C using gpuburn.

With the current fan logic, that would result in intake fans that are off.

**Comment by mmstick** [comment]
AMD GPU temperatures can be sourced from `/sys/class/drm/cardX/device/hwmon/hwmon0/temp1_input`. NVIDIA temperatures are sourced either from the nvcntrl C library included with nvidia settings, or by calling `nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader`.
