### ISSUE TITLE
Handle hotplugging of Thelio Io

### ISSUE THREAD

**Issue by jackpot51** [pop-os/system76-power#91]
This is required to support online firmware updates of Thelio Io

**Comment by jackpot51** [comment]
I think the best way to support this is to iterate through all hwmon devices, every time, instead of building a list of them when the power daemon starts

**Comment by mmstick** [comment]
Would that be more efficient than iterating through the contents of `/proc/modules`? If the I/O board has a driver module, that is.

**Comment by jackpot51** [comment]
/proc/modules does not tell you if a device is plugged in or not, just that the driver for a device is loaded

**Comment by jackpot51** [comment]
Iterating over hwmon directories each time should be very cheap
